#ifndef DYNDEF_H
#define DYNDEF_H


#ifndef PTY_NAME_LEN_MAX
#define PTY_NAME_LEN_MAX 64
#endif

#ifndef SHELL_PATH_LEN
#define SHELL_PATH_LEN 256
#endif

#ifndef MQUEUE_NAME_LEN
#define MQUEUE_NAME_LEN 512
#endif

#ifndef SHELL_IO_LEN
#define SHELL_IO_LEN 256000
#endif

#ifndef MQ_FILE_FMT
#define MQ_FILE_FMT "%d.btymq"
#endif


#ifndef ZERO_OUT
#define ZERO_OUT(BUFF, LEN) memset(BUFF, 0, LEN)
#endif

#ifndef DATA_COPY
#define DATA_COPY(DST_BUFF, SRC_BUFF, LEN) memmove(DST_BUFF, SRC_BUFF, LEN)
#endif

#if !defined(MSG_DELIVER_ERR_MSG_TXT) && !defined(MSG_DELIVER_ERR_MSG_LEN)
#define MSG_DELIVER_ERR_MSG_TXT "Failed to relay command to shell process"
#define MSG_DELIVER_ERR_MSG_LEN 45
#endif

#ifndef SWAP_AREA_LEN
#define SWAP_AREA_LEN 64000
#endif


#ifndef __SIZEOF_LONG_LONG__
#define __SIZEOF_LONG_LONG__ sizeof(unsigned long long)
#endif


#if !defined(BSDPTY_MASTER_CHARX1_BEG) && !defined(BSDPTY_MASTER_CHARX1_END)
#define BSDPTY_MASTER_CHARX1_BEG 'p'
#define BSDPTY_MASTER_CHARX1_END 'z'
#endif

#if !defined(BSDPTY_MASTER_CHARX2_BEG) && !defined(BSDPTY_MASTER_CHARX2_END)
#define BSDPTY_MASTER_CHARX2_BEG 'a'
#define BSDPTY_MASTER_CHARX2_END 'e'
#endif

#if !defined(BSDPTY_MASTER_CHARY1_BEG) && !defined(BSDPTY_MASTER_CHARY1_END)
#define BSDPTY_MASTER_CHARY1_BEG '0'
#define BSDPTY_MASTER_CHARY1_END '9'
#endif

#if !defined(BSDPTY_MASTER_CHARY2_BEG) && !defined(BSDPTY_MASTER_CHARY2_END)
#define BSDPTY_MASTER_CHARY2_BEG 'a'
#define BSDPTY_MASTER_CHARY2_END 'f'
#endif

#if !defined(BSDPTY_SLAVE_CHARX1_BEG) && !defined(BSDPTY_SLAVE_CHARX1_END)
#define BSDPTY_SLAVE_CHARX1_BEG 'p'
#define BSDPTY_SLAVE_CHARX1_END 'z'
#endif

#if !defined(BSDPTY_SLAVE_CHARX2_BEG) && !defined(BSDPTY_SLAVE_CHARX2_END)
#define BSDPTY_SLAVE_CHARX2_BEG 'a'
#define BSDPTY_SLAVE_CHARX2_END 'e'
#endif

#if !defined(BSDPTY_SLAVE_CHARY1_BEG) && !defined(BSDPTY_SLAVE_CHARY1_END)
#define BSDPTY_SLAVE_CHARY1_BEG '0'
#define BSDPTY_SLAVE_CHARY1_END '9'
#endif

#if !defined(BSDPTY_SLAVE_CHARY2_BEG) && !defined(BSDPTY_SLAVE_CHARY2_END)
#define BSDPTY_SLAVE_CHARY2_BEG 'a'
#define BSDPTY_SLAVE_CHARY2_END 'f'
#endif

#ifndef BSDPTY_MASTER_CHARX1_RANGE (BSDPTY_MASTER_CHRX1_END - BSDPTY_MASTER_CHARX1_BEG)
#ifndef BSDPTY_MASTER_CHARX2_RANGE (BSDPTY_MASTER_CHRX2_END - BSDPTY_MASTER_CHARX2_BEG)
#ifndef BSDPTY_MASTER_CHARY1_RANGE (BSDPTY_MASTER_CHRX1_END - BSDPTY_MASTER_CHARY1_BEG)
#ifndef BSDPTY_MASTER_CHARY2_RANGE (BSDPTY_MASTER_CHRX2_END - BSDPTY_MASTER_CHARY2_BEG)

#ifndef BSDPTY_SLAVE_CHARX1_RANGE (BSDPTY_SLAVE_CHRX1_END - BSDPTY_SLAVE_CHARX1_BEG)
#ifndef BSDPTY_SLAVE_CHARX2_RANGE (BSDPTY_SLAVE_CHRX2_END - BSDPTY_SLAVE_CHARX2_BEG)
#ifndef BSDPTY_SLAVE_CHARY1_RANGE (BSDPTY_SLAVE_CHRX1_END - BSDPTY_SLAVE_CHARY1_BEG)
#ifndef BSDPTY_SLAVE_CHARY2_RANGE (BSDPTY_SLAVE_CHRX2_END - BSDPTY_SLAVE_CHARY2_BEG)

#if !defined(BSDPTY_MASTER_PATH_SEQ) && !defined(BSDPTY_MASTER_PATH_LEN)
#define BSDPTY_MASTER_PATH_SEQ '/', 'd', 'e',  'v', '/', 'p', 't', 'y'
#define BSDPTY_MASTER_PATH_LEN 8
#endif

#if !defined(BSDPTY_SLAVE_PATH_SEQ) && !defined(BSDPTY_SLAVE_PATH_LEN)
#define BSDPTY_SLAVE_PATH_SEQ '/', 'd', 'e',  'v', '/', 't', 't', 'y'
#define BSDPTY_SLAVE_PATH_LEN 8
#endif



#endif